---
- name: Build Nginx
  community.docker.docker_compose_v2:
    project_src: "{{ inception }}"
    services:
      - nginx
    state: stopped
    build: always
  when: cmd == 'build'

- name: Start Nginx
  community.docker.docker_compose_v2:
    project_src: "{{ inception }}"
    services:
      - nginx
    state: present
    build: always
  when: cmd == 'start'

- name: Stop Nginx
  community.docker.docker_compose_v2:
    project_src: "{{ inception }}"
    services:
      - nginx
    state: stopped
  when: cmd == 'stop'

- name: Restart Nginx
  community.docker.docker_compose_v2:
    project_src: "{{ inception }}"
    services:
      - nginx
    state: restarted
  when: cmd == 'restart'
