---
- name: Build Portainer
  community.docker.docker_compose_v2:
    project_src: "{{ inception }}"
    services:
      - portainer
    state: stopped
    build: always
  when: cmd == 'build'

- name: Start Portainer
  community.docker.docker_compose_v2:
    project_src: "{{ inception }}"
    services:
      - portainer
    state: present
    build: always
  when: cmd == 'start'

- name: Stop Portainer
  community.docker.docker_compose_v2:
    project_src: "{{ inception }}"
    services:
      - portainer
    state: stopped
  when: cmd == 'stop'

- name: Restart Portainer
  community.docker.docker_compose_v2:
    project_src: "{{ inception }}"
    services:
      - portainer
    state: restarted
  when: cmd == 'restart'
