---
install_deps:
  - ca-certificates
  - lsb-release
  - gnupg
  - python3
  - python3-pip

docker_install:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin

docker_uninstall:
  - docker.io
  - docker-doc
  - docker-compose
  - docker-compose-v2
  - podman-docker
  - containerd
  - runc
