# -*- mode: ruby -*-
# vi: set ft=ruby :

CPU = 1
MEMORY = 1024
IP_SERVER = "192.168.56.110"
IP_WORKER = "192.168.56.111"
ALPINE_VERSION = "319"
BOX_VERSION = "4.3.12"

Vagrant.configure("2") do |config|
    config.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--cpus", CPU]
        vb.customize ["modifyvm", :id, "--memory", MEMORY]
        vb.linked_clone = true
    end

    {"#{ENV['USER']}S" => IP_SERVER, "#{ENV['USER']}SW" => IP_WORKER}.each do |hostname, ip|
    config.vm.define hostname do |vm_config|
      vm_config.vm.box = "generic/alpine#{ALPINE_VERSION}"
      vm_config.vm.box_version = BOX_VERSION
      vm_config.vm.hostname = hostname
      vm_config.vm.network "private_network", ip: ip
      vm_config.vm.provider "virtualbox" do |vb|
        vb.name = hostname
      end
      script_path = hostname.include?("SW") ? "./scripts/worker.sh" : "./scripts/server.sh"
      vm_config.vm.provision "shell", path: script_path
    end
  end
end